### ISSUE TITLE
Cannot run client test on mac osx

### ISSUE THREAD

**Issue by xuanthuong** [bwilcox-1234/ChatScript#104]
When I run command <./MacChatScript client=localhost:1024>, It shows <CommandLine: client=localhost:1024> and then exit.

**Comment by bwilcox-1234** [comment]
in the exit or bugs log, it probably tells you something

**Comment by marcjay** [comment]
I had the same issue I think:

```
$ ./MacChatScript client=localhost:1024
CommandLine: /Users/marcjay/Documents/MacChatScript
    client=localhost:1024

evcalled pid: 64586
```

For whatever reason, when compiling on a Mac (which has the __MACH__ compiler flag set), the client is discarded:
https://github.com/bwilcox-1234/ChatScript/blob/v7.31/SRC/common.h#L69
```
#elif __MACH__
#define DISCARDCOUNTER 1
#define DISCARDCLIENT 1    // <-- THIS LINE HERE
#define DISCARDPOSTGRES 1
#define DISCARDMYSQL 1
```
This looks to me like a bug. To fix, I removed/commented out this line, ran ```make``` and then ran the resulting BINARIES/ChatScript binary that gets created. That then has the client code in it and fixes the issue.

@bwilcox-1234 it would be good to know if there's a reason the client is disabled by default in the Mac OS binary?

Many thanks

**Comment by bwilcox-1234** [comment]
fixed in master for next deliver. No reason per se, other than copying unnecessarily.

**Comment by marcjay** [comment]
Great, many thanks for the merge
