### ISSUE TITLE
Bad Binary Dictionary Entry on Mac

### ISSUE THREAD

**Issue by Citronelol** [bwilcox-1234/ChatScript#110]
Hi, 

Following the getting started tutorial, I cloned the repo, went into BINARIES, launched ./MacChatScript local as advised and faced the following error :

``
Bad Binary Dictionary entry, rebuild the binary dictionary ??
``

Should I follow another step before launching my first bot?
Thanks

**Comment by solyaris** [comment]
Hi 
try to rebuild the dictionary;

* launch  ./MacChatScript local 
*` :build 0`

**Comment by Citronelol** [comment]
Hi,

Thank you for your help. Actually, the error appears when launching CS with 

``
$ ./MacChatScript local
``

and immediately closes the CS console, stopping me from typing any additional command

**Comment by pdesgarets** [comment]
@Citronelol same here. Resolved by building again (`cd SRC && make && ../BINARIES/ChatScript local`)

**Comment by Citronelol** [comment]
It works ! Thanks a lot for your help.
