### ISSUE TITLE
Using the wordnet for synonym detection

### ISSUE THREAD

**Issue by Tobi-La** [bwilcox-1234/ChatScript#119]
First, I am sorry to ask this here, my concern would better fit to the forum, but I do not have forum access since months...

I know that chatscript autogenerates many concepts like ~color from the wordnet, but the wordnet already has synonyms that aren't available in concepts.

E.g.
Wordnet knows that abductor and kidnapper are synonyms:

> :word abductor

```
abductor (7679):
  Properties: NOUN NOUN_SINGULAR
  SystemFlags: common2  POS-tiebreak: NOUN
  ParseBits:
  InternalBits: 0
  Other:     canonical: abductor
  Meanings:
    noun
    2: kidnapper~1 someone who unlawfully seizes and detains a victim
      synonyms:  *kidnapper~1  snatcher~1  kidnaper~1  abductor~2
    1: abductor_muscle~1 a muscle that draws a body part away from the median line
      synonyms:  *abductor_muscle~1  abductor~1
  MultiWordHeader length: 2
  Direct Sets:
  Facts:
```

How do I write a pattern that uses those synonyms? Or how do I match the meaning kidnapper~1 in chatscript, so that every word that has this meaning listed in wordnet is matched?

**Comment by bwilcox-1234** [comment]
if your pattern names the meaning, like kidnapper~1, then it will match abductor and kidnapper as input

**Comment by Tobi-La** [comment]
I use :common to find out if two words are in the same concept.
Is there a way to do the same with meanings too?
like :common abductor kidnapper returns e.g. kidnapper~1
