### ISSUE TITLE
ä,ö,ü for German language

### ISSUE THREAD

**Issue by inventorix** [bwilcox-1234/ChatScript#121]
Hi everybody,

I am having a look with the command :prepare on german sentences that use 
letters ü,ö,ä.

When I try to store the input sentence with: u: (_*) $saved = '_0 
CS always replaces ü,ö,ä with a white space although I started the German language with
the command line parameter language=German.

Is there a way to fix this issue. Thanks for contribution.

**Comment by bwilcox-1234** [comment]
start by turning off spell checking

**Comment by inventorix** [comment]
Thanks for the fast response. 
I just turned it off. Unfortunately there is no difference.

E.g:
:prepare nächstes 
Original User Input: n  chstes
Actual used input: n chstes 

The goal is to have a spell checked "actual used input" with ä,ö,ü in it.
Thanks.

**Comment by NewInnovation** [comment]
Hello,

I suspect I am having a similar problem with the swedish language. The script is written in english, but I do want to be able to extract swedish names/cities etc. Removing the spellchecker makes 'ä' work but strangely substitutes 'ö' to " and 'å' to 'Ø'. 

Without removing spell checker (pseudo):
u: ( ä ) User wrote ä 
u: ( å ) User wrote å
u: ( ö ) User wrote ö

user> ä
bot> User wrote ä
user> å
bot> User wrote Ø
user> ö
bot> ( no response )

Everything is encoded in utf-8. For the 'å', I suppose there must be some substitution going on that I cannot see, removing system substitutions, however, has no effect.

Not sure what is going on. Would greatly appreciate some insight here.
Thanks a bunch.

**Comment by bwilcox-1234** [comment]
It worked for me using german.  From trimmed logfile:
  ä ==> User wrote ä  
  å ==> User wrote å  
  ö ==> User wrote ö  
But if you look at the console, since Visual Studios console cannot handle utf8 full range of characters (only extended ascii), the console can look wrong while the log looks right.
