### ISSUE TITLE
New ^respond(value TEST) optional parameter

### ISSUE THREAD

**Issue by Tobi-La** [bwilcox-1234/ChatScript#147]
Hi Bruce,
How do I use the new optional parameter test of ^respond() ?
I want to check if a topic would match the current input without executing the topic. The new optional parameter TEST seems to be perfect for this.
 The doc says that if it matches it returns the rule id.
But if I try `$$test = ^respond($$_topic TEST)`  the compiler gives me an error: 

> ^respond always returns null, so assignment is pointless

I even tried TEST and FAIL to determine if the match occured or not, but i didn't work either.

Thank you!

**Comment by bwilcox-1234** [comment]
nasty compiler. now fixed for next release.
