### ISSUE TITLE
unknown-word problem

### ISSUE THREAD

**Issue by ehion** [bwilcox-1234/ChatScript#154]
topic: ~introductions keep repeat []

t: [Hello] [Hi] [Hey], I will help you plan your travel. Just tell me where you are and
where you want to go to.

u: (be * at _*)
OK, you want to go from _0.
$source = '_0
I used this as the .top file when i built my own robot,but error came when i sent the message:"be at qfqvqvqe" and got the reply "OK, you want to go from unknown-word."
Here is my question:Only the unknown-word in dictionary can the robot recognize it and answer in the right way?
it is too difficult to build a dictionary covers all the word person might tell to the robot,how can we fix it?

**Comment by bwilcox-1234** [comment]
dont use _0, use '_0
