### ISSUE TITLE
^disable is not working for rules outside the current topic

### ISSUE THREAD

**Issue by Tobi-La** [bwilcox-1234/ChatScript#159]
If the rule is not part of the current topic, it doesn't get disabled:
Can be reproduced with the following code:
```

topic:  ~car[car]
u: CAR (car) i have a car


topic: ~test share keep repeat[ test]

u: (test 1) test 1 ^disable(RULE ~car.CAR)
```

**Comment by bwilcox-1234** [comment]
This test WORKED for me, after I changed the name of the ~car topic, which the script compiler COMPLAINS about because there is already a concept called ~car

**Comment by Tobi-La** [comment]
Ok, I was using 7.52 and the problem occured even after renaming the topic.
I tried again with 7.54 and it was working. So the issue is fixed, thank you very much Bruce :)
