### ISSUE TITLE
Local output breaks utf-8 encoded characters

### ISSUE THREAD

**Issue by jarozajac** [bwilcox-1234/ChatScript#160]
Hi,
it looks like chatscript breaks utf-8 encoded characters outputing to console when ran with the local parameter. The same bot ran in client/server mode with the same files (without rebuilding the bot when switching from local to client/server) outputs the characters correctly. I tried saving the topic file as UTF8 with and withou BOM, tried running it in a windows (with chcp 65001) and linux shell, always with the same result.

Sample topic file:

```
topic: ~main []
 
t: Ahoj, vítam Ťa na stránke! Ako Ti môžem pomôcť?
```
Sample output:

`Ahoj, v�tam Ťa na str�nke! Ako Ti m�žem pom�cť?`

**Comment by bwilcox-1234** [comment]
the log file will be correct. The console of visual studio cannot handle it and I cant control that.
