### ISSUE TITLE
`?` comparison test

### ISSUE THREAD

**Issue by EnguGH** [bwilcox-1234/ChatScript#161]
The `?` comparison triggers the following error : 
```,PATTERN-57 Cannot use _ before a comparison``` 

I'm trying to do it just like in the docs :
```
u: ( _~propername?~bands )
```
https://github.com/bwilcox-1234/ChatScript/blob/master/WIKI/ChatScript-Advanced-User-Manual.md#more-comparison-tests----

When not using the `_`, the build passes, but the rule doesn't seem to match anything.

Thanks !

**Comment by bwilcox-1234** [comment]
doc change because it is not legal, do u: (_~propername '_0?~bands)

**Comment by EnguGH** [comment]
Thanks !

Is there a way to do this without capturing the word ?
Something like : `~propername?~bands` without the `_`.

**Comment by bwilcox-1234** [comment]
yes. it was just the test AND capture that was illegal

**Comment by EnguGH** [comment]
Indeed without the `_`, the build passes.

Yet, I'm running version 7.54, and the sentence `you love ski`
matches : `u: (you love ~tool)` and `u: (you love ~winter_sports)`
but doesn't match `u: (you love ~tool?~winter_sports)`

Am I doing anything wrong ?
