### ISSUE TITLE
Why Rejoinders

### ISSUE THREAD

**Issue by gazugafan** [bwilcox-1234/ChatScript#167]
Is there any special configuration needed for ~why rejoinders to work? I've added the following to the Harry bot to test them...
```
t: Does the why rejoinder work?
    a: (~why) Because.
    a: (~no) No?
    a: (~yes) Yes?
```

I would expect to be able to ask "why?" after the gambit about rejoinders working, have the bot respond "Because.", and then have the bot pretend the why and its answer were never issued and directly move on to real rejoinders if the user answers the question still pending. It doesn't seem to be working like that, though...

```
HARRY:  Welcome to ChatScript.
: > hi
HARRY:  Have you been here before?
: > no
HARRY:  Then welcome to your first time.
: > thanks
HARRY:  Does the why rejoinder work?
: > why?
HARRY:  Because.
: > yes
HARRY:  Did you run away from home when you were little?
(would have expected the bot to retry the other rejoinders and respond with "Yes?")
```

**Comment by solyaris** [comment]
Hi Ken

> (would have expected the bot to retry the other rejoinders and respond with "Yes?")

no... following your call flow example, code works as expected; rejoinder rule `a: (~why) Because.`  fire (output is printed), so the rule complete;  maybe instead you would want to use setRejoinder, see:
https://github.com/solyaris/ChatScript/blob/master/WIKI/ESOTERIC-CHATSCRIPT/ChatScript-Exotica-Examples.md#setrejoinder

**Comment by gazugafan** [comment]
Thanks for the response! Unfortunately, I'm having similar trouble with the example in the documentation you linked. It actually doesn't seem to function as intended...

```
HARRY:  If you poured coffee over me or let me fall into the bathtub what do you think would happen?
ken: > you'd get wet
HARRY:  I don't know what to say.
(would expect "And then?" and to then have the other rejoinders work)
```

And the ~why rejoinder doesn't seem to do anything special...
```
HARRY:  If you poured coffee over me or let me fall into the bathtub what do you think would happen?
ken: > why?
HARRY:  I want you to think about and understand my vulnerabilities.
ken: > you'd die
HARRY:  I don't know what to say.
(would have expected "Precisely.", as the ~why rejoinder should automatically cause the other rejoinders to be tried.)
```

I'm not sure about the first problem, but I think the second problem (regarding ~why rejoinders) is coming from my misunderstanding of this article...
https://github.com/bwilcox-1234/ChatScript/blob/master/WIKI/PAPERS/Paper%20-%20WinningTheLoebners.md#105-delayed-responses
... I'm guessing this article isn't so much a guide to how ChatScript works, but more like thoughts on what to consider including in your own control script. So, I would have to modify the control script to cause ~why rejoinders to automatically function as the article describes. Is that right?

**Comment by bwilcox-1234** [comment]
So a rejoinder captures an immediate response. A why rejoinder does that and DOES NOT AUTOMATICALLY then pursue additional rejoinders.  One can write a control script that does. In the case of the initial example, if you have a: (~why)  then you COULD test for %more and reset the input rejoinder to be back at the start of this collection and then do ^next(INPUT) and call for a rejoinder. Or even just do
a: (~why) if (%more) {^next(INPUT) ^refine(...)}  to try next piece with current rejoinder zone.  depends on what you want to do

**Comment by solyaris** [comment]
Hi Bruce,
you say that  `a: (~why) if (%more) {^next(INPUT) ^refine()}` solve the initial Ken's question, but this isn't what `^setRejoinder(FATHER-RULE)` would do?

Following Ken's test it seems that `^setRejoinder(FATHER-RULE)` described here: 
https://github.com/solyaris/ChatScript/blob/master/WIKI/ESOTERIC-CHATSCRIPT/ChatScript-Exotica-Examples.md#setrejoinder

doesn't work as expected. It's a bug?

To be sincere, also the documentation here is not fully clear to me:
https://github.com/bwilcox-1234/ChatScript/blob/master/WIKI/ChatScript-System-Functions-Manual.md#setrejoinder--kind-tag-

Maybe more example there could help.

thanks for your patience.
giorgio

**Comment by bwilcox-1234** [comment]
one could do setrejoinder as you say, but you ALSO have to terminate the current sentence with a ^fail(sentence).  I will go look at more data from examples soon

**Comment by gazugafan** [comment]
Thanks for your help, guys! I think I've come up with a working control script solution to automatically handle ~why rejoinders (and retry the other rejoinders). I put this at the top of my control script...
```
	# check for ~why rejoinder, and automatically retry other rejoinders...
	if ( %response == $_responseCount )
	{
		if (^match(~why))
		{
			nofail(TOPIC ^rejoinder())
			if ( %response != $_responseCount )
			{
				^setrejoinder(copy %inputrejoinder)
			}
		}
	}
```

That seems to solve my original problem. I don't 100% understand how that setrejoinder call resets the rejoinder back to the parent, but it does seem to work!
