### ISSUE TITLE
Harry answers a blank line

### ISSUE THREAD

**Issue by hrkucuk** [bwilcox-1234/ChatScript#17]
Hello,

I'm running the Chatbot on a linux machine, (Xubuntu 14.04.5, x64). When I run the bot as seen in the screenshot, it gives me blank lines as an answer, except the first line.

When I run with `./LinuxChatScript64 local` command, the result is same.
Any Ideas? Thanks.

![blank_line_issue](https://cloud.githubusercontent.com/assets/16069894/19021172/00ad58ea-88bc-11e6-8f18-cc12897cfc25.png)

**Comment by solyaris** [comment]
Hi
Did you done a `:build Harry` command ?
Is `RAWDATA/HARRY` like this:
https://github.com/bwilcox-1234/ChatScript/tree/master/RAWDATA/HARRY ?

giorgio

**Comment by hrkucuk** [comment]
Oh Hi Giorgio! Yes that folder was looking exactly as the link you provided.But, well, yes after running :build Harry command within the conversation, it started to talk to me! It was having me a long lasting conversation about my childhood, never seen something like this. It is amazing!However, when I reset the conversation with :reset command, it was asking me the same questions.That make sense, however. How did you figure that ':build Harry' out?Thanks a lot for your help! best regards,Hakki Riza.  03.10.2016, 10:07, "Giorgio Robino" <notifications@github.com>:HiDid you done a :build Harry command ?Is RAWDATA/HARRY like this:https://github.com/bwilcox-1234/ChatScript/tree/master/RAWDATA/HARRY ?giorgio—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.   Best regards,Hakkı Rıza Küçük.

**Comment by solyaris** [comment]
Hi Hakki

> How did you figure that ':build Harry' out?

see:
 
https://github.com/bwilcox-1234/ChatScript/blob/master/wiki/ChatScript-Debugging-Manual.md
https://github.com/bwilcox-1234/ChatScript/blob/master/wiki/PREDEFINED-BOTS/Bot-Harry.md

Original PDF docs here:
https://github.com/bwilcox-1234/ChatScript/tree/master/PDFDOCUMENTATION

I'm contributing a bit to translate / update / pretty print above docs here:
https://github.com/bwilcox-1234/ChatScript/tree/master/wiki
 
I guess this issue could be closed :)
giorgio

**Comment by hrkucuk** [comment]
Yep, thanks again Giorgio!

Closing ISSUE #17
