### ISSUE TITLE
Chatscripts with Postgres

### ISSUE THREAD

**Issue by DukeKadho** [bwilcox-1234/ChatScript#177]
hi, i git you project and try to build the postgres demo chatbot. I have installed the postgresql locally. But the system show me the " *** Error- Undefined function ^dbexecute" and "*** Error- Undefined function ^dbinit". Could you tell me waht the problem is and how can i fix it? thanks a lot

**Comment by bwilcox-1234** [comment]
CS only ships with std server. You need to stand in SRC directory and type "make pgserver" and then use that version
