### ISSUE TITLE
[question] I try to read  ( \[ Text \] _* ) but I can't.

### ISSUE THREAD

**Issue by ohnewdev** [bwilcox-1234/ChatScript#178]
Hi. I love this project and I try to make chat program. :)
Could I put some question?
```
# ==============================
# I cant get any input with the following pattern. 
#! [Request No] 12345
u: TEST_SPECIAL_CHA1 ( \[ Request No \] _* )
^"ok1"
'_0
```

```
# ==============================
# this one works!!
#! Request No] 12345
u: TEST_SPECIAL_CHA2 ( Request No \] _* )
^"ok2"
'_0
```

**Comment by bwilcox-1234** [comment]
The issue is that OOB data in [ ] is treated as a sentence all by itself. So your input consists of 2 sentences and you cannot match both simultaneously.  Are you using  [ ] as intending oob data or what?
