### ISSUE TITLE
Sentence ending question

### ISSUE THREAD

**Issue by rschuetzler** [bwilcox-1234/ChatScript#182]
The basic user manual has the following line:

> One can also disable sentence ending.

I have not been able to find how to disable sentence ending anywhere. I've scoured the docs, but maybe I'm just not looking for the right thing. How would one disable sentence ending? And if I did that, would the user message 

> What's your name? My is Alfred; I'm from London.

be processed as all one sentence, aka:

> What's your name my is Alfred I'm from London

**Comment by bwilcox-1234** [comment]
$cs_token has values. One can be #NO_SENTENCE_END
