### ISSUE TITLE
How to create my chatbot? (tutorial is vague for me)

### ISSUE THREAD

**Issue by roboticslover** [bwilcox-1234/ChatScript#191]
I built a file named TEST like this: 
`mkdir ../RAWDATA/TEST` 
Then I created a file named `filesmine.txt` inside the RAWDATA with this content:
```
RAWDATA/QUIBBLE/

RAWDATA/HARRY/simplecontrol.top # default bot control
RAWDATA/TEST/tutorial.top # tutorial bot data

```
Then I created another file named `tutorial.top` inside the `TEST` folder with this content:
```
```

topic: ~introductions []

t: Hello, talk to me!

```
But now, I don't know where should I run this command:
`:build mine`

**Comment by bwilcox-1234** [comment]
run the chatscript engine and type that as input at the prompt
