### ISSUE TITLE
Linux compile script errors

### ISSUE THREAD

**Issue by nodgesoft** [bwilcox-1234/ChatScript#2]
g++ -funsigned-char src/*.cpp -O2  -DDISCARDDATABASE=1 -o LinuxChatScript -lpthread -lrt 2>>err.txt

Should be:

g++ -funsigned-char SRC/*.cpp -O2  -DDISCARDDATABASE=1 -o LinuxChatScript -lpthread -lrt -lcurl 2>>err.txt

Summary:
1. Add -lcurl
2. Change case of SRC directory name.

**Comment by bwilcox-1234** [comment]
agreed. I have fixed this.

Most people follow directions of standing in the SRC directory and typing
make server. Which does this correctly.

On Thu, Feb 18, 2016 at 8:24 PM, nodgesoft <notifications@github.com> wrote:

> g++ -funsigned-char src/*.cpp -O2 -DDISCARDDATABASE=1 -o LinuxChatScript
> -lpthread -lrt 2>>err.txt
>
> Should be:
>
> g++ -funsigned-char SRC/*.cpp -O2 -DDISCARDDATABASE=1 -o LinuxChatScript
> -lpthread -lrt -lcurl 2>>err.txt
>
> Summary:
> 1. Add -lcurl
> 2. Change case of SRC directory name.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bwilcox-1234/ChatScript/issues/2>.
>



-- 
CEO of Brillig Understanding Inc.  (Natural Language applications)
brilligunderstanding.com
805-547-1109

**Comment by nodgesoft** [comment]
Perhaps just change compile bash script to "cd ../SRC/; make server "

Just a thought.

**Comment by bwilcox-1234** [comment]
fine thought. done.

On Thu, Feb 18, 2016 at 8:32 PM, nodgesoft <notifications@github.com> wrote:

> Perhaps just change compile bash script to "cd ../SRC/; make server "
>
> Just a thought.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bwilcox-1234/ChatScript/issues/2#issuecomment-186045732>
> .
>



-- 
CEO of Brillig Understanding Inc.  (Natural Language applications)
brilligunderstanding.com
805-547-1109
