### ISSUE TITLE
git clone from master failing.

### ISSUE THREAD

**Issue by claytantor** [bwilcox-1234/ChatScript#20]
It looks like something committed is breaking clones. I have never sean this before.

```
bwilcox-1234 $ git clone https://github.com/bwilcox-1234/ChatScript.git
Cloning into 'ChatScript'...
remote: Counting objects: 4200, done.
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
```

I have tested this on both Mac and Ubuntu

```
$ git --version
git version 2.9.3 (Apple Git-75)
```

**Comment by kuzyn** [comment]
Hey @claytantor, have a look at this:
https://confluence.atlassian.com/bbkb/error-rpc-failed-result-18-http-code-0-301663284.html

I would also recommend switching to ssh authentication for github, which is a lot more convenient and would also make this problem disappear:
https://help.github.com/articles/adding-a-new-ssh-key-to-your-github-account/

**Comment by claytantor** [comment]
Gotcha. Will try and report back.

**Comment by tkuebler** [comment]
Did this get resolved?  Can it be closed?

**Comment by claytantor** [comment]
verified working with ssh

```
$ git clone git@github.com:bwilcox-1234/ChatScript.git
Cloning into 'ChatScript'...
X11 forwarding request failed on channel 0
remote: Counting objects: 4859, done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 4859 (delta 2), reused 0 (delta 0), pack-reused 4852
Receiving objects: 100% (4859/4859), 350.58 MiB | 2.65 MiB/s, done.
Resolving deltas: 100% (3192/3192), done.
Checking out files: 100% (1221/1221), done.
 $
```
