### ISSUE TITLE
:trace works only in local mode?

### ISSUE THREAD

**Issue by selfyguy** [bwilcox-1234/ChatScript#202]
Hello,

I have setup ChatScript (on windows) for interaction/development in four ways:

1. run CS as server (top left window in image below)
2. run CS as client (bottom left window in image)
3. run CS as local (right window in image)
4. run a nodejs app that acts as a message broker between CS and a web browser.
    The node app directly communicates with the server instance running in (1) above.

When I issue a :trace command from 2, 3 or 4, i get trace messages only in (3). 
Shouldn't CS be giving trace messages along with responses in (2) and (4) too?

Or is there a setting / additional command that I need to enable to get those messages in (2) and (4)?

For example:
I issue `:trace simple` from (2) or (4). But subsequent volleys don't output any trace information in either windows. I then go to console of (3);where I did NOT execute the` :trace` command; and here I get trace messages for all volleys/interactions on this console.

I guess the `:trace` command sets universally per installation that works across all running instances. If so, why don't the trace messages get output in all instances?

Thanks.

![shot](https://user-images.githubusercontent.com/34223101/35469576-8114eb7a-035d-11e8-87df-83ad406c5e7b.jpg)

**Comment by yaleimeng** [comment]
Yes , :trace command works well in local mode.  (Because it is also called debug/test mode)
But Client/Serer mode is for production environment ,  you can't trace internal things.
