### ISSUE TITLE
version 8.0 seems not finished ?

### ISSUE THREAD

**Issue by yaleimeng** [bwilcox-1234/ChatScript#203]
I can finish compiling on Ubuntu 16.04 and win10 64bit, but the binary file  run ( local mode ) with error.
on ubuntu , like this:
>    in cs_init.txt at 0: 
    Error opening utf8writeappend file LOGS/startlog.txt: No such file or directory
Segmentation fault

on windows10  , when run the original chatscript.exe file , it crashed.
Then I compile this project , no erros.  But when I run the new  chatscript.exe , it crashed again.

Is this a problem ?

**Comment by ludan-av** [comment]
I use the 8.0 version available on https://sourceforge.net/projects/chatscript/

I just managed building and running one of my basic bots without any problem (Windows 10 64, French language for CS).

**Comment by DougDanforth** [comment]
I have to manually create a folder called LOGS in ChatScript then the program will launch.

**Comment by yaleimeng** [comment]
@DougDanforth Thanks for your information.  I makedir LOGS ,and it run normally this time.
@ludan-av Thanks for your information, too.

**Comment by rezaee** [comment]
I got this error message too!

**Comment by yaleimeng** [comment]
This project is moved to [ChatScript](https://github.com/ChatScript/ChatScript). And the latest version is 8.2 now.
@rezaee
