### ISSUE TITLE
jsonparse & permanent in CS 7.0 

### ISSUE THREAD

**Issue by ludan-av** [bwilcox-1234/ChatScript#31]
With this code:
```
$_dataRaw
$data = ^jsonparse($_dataRaw)
$data.firstName
```
the Output in CS 7.0 is:
`{ "firstName": "André" }  André`
(which looks ok)

When I just add "permanent":
```
$_dataRaw
$data = ^jsonparse(permanent $_dataRaw)
$data.firstName
```
the Output in CS 7.0 becomes:
`{ "firstName": "André" }`
(whichs looks wrong)

**Comment by bwilcox-1234** [comment]
This example works perfectly for me:
topic: ~introductions  keep repeat()
t: hi there 
u: LABEL(test ) $_dataraw = ^' { "firstName": "André" } '
   $_x =  ^jsonparse(permanent $_dataraw) 
	$_x.firstName
	$_dataX = "hello"
	$_x.firstName

email me a topic in which this fails.

**Comment by ludan-av** [comment]
Here is the minimalist code to produce the issue:
```
topic: ~debut repeat []

t: choose Andre ^keep()

u: (Andre)
  $_dataRaw = ^'
  {
    "civilite": "M.",
    "firstName": "André"
  }
  '

u: ($_dataRaw)  

  $_dataRaw
  $data = ^jsonparse(permanent $_dataRaw)
  $data.firstName

```

Without "permanent", $data.firstName produces "André". With permanent, it does not.

**Comment by bwilcox-1234** [comment]
fixed (see prior note on other bug)
