### ISSUE TITLE
quotation marks issue (a small one)

### ISSUE THREAD

**Issue by ludan-av** [bwilcox-1234/ChatScript#32]
```aaa "xxxx" bbb``` produces ```Aaa "xxxx"bbb```

```aaa \" xxxx \" bbb``` produces ```Aaa "xxx bbb```

I'd like to produce ```Aaa "xxx" bbb```

**Comment by bwilcox-1234** [comment]
use active strings ^' aaa "xxxx" bbb'

**Comment by ludan-av** [comment]
thanks !
