### ISSUE TITLE
Integrating with chatterbot

### ISSUE THREAD

**Issue by aliabbasjp** [bwilcox-1234/ChatScript#33]
Hi,
I need to integerate https://github.com/gunthercox/ChatterBot with your chatscript such that a new responseadapter named "Chatscript" is possible.
How can I start using chatscript from python to achieve this?

**Comment by tkuebler** [comment]
This is better asked at the chatbots.org forum, where most of the technical support for chatscript happens.  Ie, it's not a bug or issue with chatscript, more of a beginner user question which is answered in the manual.

There are basically two ways - I would recommend the first unless you are advanced, can wade through hard technical problems without help and need high native performance without network:

1. connect to a server over tcp - this method is clearly documented in the manual.  Resources to get you started:

    - https://github.com/bwilcox-1234/ChatScript/blob/master/PDFDOCUMENTATION/CLIENTS-AND-SERVERS/ChatScript-ClientServer-Manual.pdf
    - https://www.chatbots.org/ai_zone/viewthread/397/P60/#5062

2. compile chatscript as a library and use pythons native library facility to call it directly in process.  Resource to get you started with that:

    - https://www.chatbots.org/ai_zone/viewthread/1552/P30/
    - http://vinterstitial.blogspot.com/2014/05/a-swig-of-chatbot-making-unity-chatter.html


Good luck.
