### ISSUE TITLE
Command line interface enhancements

### ISSUE THREAD

**Issue by solyaris** [bwilcox-1234/ChatScript#44]
Hi Bruce,

> here below minor command line enhancements / proposals,  to speed up edit/build cycles  during **development phase** through console interaction  mode (ChatScript local).
> BTW, I run ChatScript from an headless linux ubuntu terminal.

# 1.  Build & run at once
>Proposal

Now, the development phase require these steps:

1. edit your bot code (let say the bot is demo Harry)
2. compile by example with command line
```bash
$  BINARIES/LinuxChatScript64 local build1=filesHarry.txt
```

The above command, despite the **local** parameter just BUILD and exit, without RUNNING the interactive shell :-(

```
----Reading file eliza_or.top
Reading topic ~quibble_or

----Reading file eliza_why.top
Reading topic ~quibble_why

<<end folder RAWDATA/QUIBBLE
No errors or warnings

Finished compile

$ 
```

3. if I there's no errors  during building, I have to re-launch CS, re-entering command again, passing username *giorgio, avoiding to repeat every time user name at login.

```bash
$  BINARIES/LinuxChatScript64 local login=giorgio
```

**Change request:**
What I'd like, in case of **no build errors**, is to leave coexist *local* and *build1* parameters, to build & run **at once**, with this possible command line:
```bash
$  BINARIES/LinuxChatScript64 local build1=filesHarry.txt login=giorgio
```

# 2. Reset dialog from command line 
> question/bug?

To restart dialog with a user from beginning with command *:reset*, the command line doesn't run:

```bash
$  BINARIES/LinuxChatScript64 local build1=filesHarry.txt login=giorgio bootcmd=reset
CommandLine:
    local
    login=giorgio
    bootcmd=reset

ChatScript EVSERVER Version 7.111 pid: 1243 64 bit LINUX compiled Jan 16 2017 04:54:53 host=local
Params:   dict:2097151 fact:800000 text:100000kb hash:100000
          buffer:80x80kb cache:1x5000kb userfacts:100 outputlimit:80000 loglimit:80000
WordNet: dict=214033  fact=85706  heap=12701684 Jan15'17-12:54:50
Build0:  dict=67751  fact=129101  heap=1145956 Compiled:Jan21'17-18:56:16 by version 7.111 "0"
Build1:  dict=169  fact=22  heap=212352 Compiled:Jan22'17-11:56:21 by version 7.111 "Harry"
Used 60MB: dict 281,954 (24811kb) hashdepth 14/1 fact 214,829 (10311kb) heap 14183kb
           buffer (6400kb) cache (5000kb) POS: 918 (29kb)
Free 113MB: dict 1,815,197 hash 13580 fact 585,171 stack/heap 85,816KB

    Dictionary building disabled.

HARRY:  Hello, again.
giorgio: >
```

I'd wish to reset dialog from command line instead, as I did:

```
giorgio: > :reset
HARRY:  Welcome to ChatScript.
```

It's a bug?

# 3.  Building errors
> Proposal.

I propose to put building errors in standard error stream (stderr).
That could also help to quickly edit errors within a standard editor.
BTW, maybe I'd suggest to use a c compiler-like format to easily browse errors in vim cwindows or similar tool in other editor). Example:

```bash
test.top:7: error: expecting responder for topic ~introductions, got -------
```

Now instead, I  got following info in stdout:

```
----Reading file test.top
Reading topic ~introductions
*** Error- line 4 of test.top:
   in test.top at 4: -------

Expecting responder for topic ~introductions, got -------
 ERROR SUMMARY:
  line 4 of test.top:
Expecting responder for topic ~introductions, got -------
1 errors - press Enter to quit. Then fix and try again.
```

# 4. Run a specific bot
>Question/bug.

Can I run a conversation with a bot I built "in past" before having built a current bot ?
For example:
step 1. I build bot Harry.
step 2.  I build bot Test
step 3. I want to run bot Harry ; now I expected to pass parameter: *login=giorgio:Harry*, but it seems not working:

```
# BINARIES/LinuxChatScript64 local login=giorgio:Harry
CommandLine:
    local
    login=giorgio:Harry

ChatScript EVSERVER Version 7.111 pid: 1700 64 bit LINUX compiled Jan 16 2017 04:54:53 host=local
Params:   dict:2097151 fact:800000 text:100000kb hash:100000
          buffer:80x80kb cache:1x5000kb userfacts:100 outputlimit:80000 loglimit:80000
WordNet: dict=214033  fact=85706  heap=12701684 Jan15'17-12:54:50
Build0:  dict=67751  fact=129101  heap=1145956 Compiled:Jan21'17-18:56:16 by version 7.111 "0"
Build1:  dict=8  fact=1  heap=2780 Compiled:Jan22'17-13:05:14 by version 7.111 "test"
Used 60MB: dict 281,793 (24797kb) hashdepth 14/1 fact 214,808 (10310kb) heap 13973kb
           buffer (6400kb) cache (5000kb) POS: 918 (29kb)
Free 114MB: dict 1,815,358 hash 13580 fact 585,192 stack/heap 86,026KB

    Dictionary building disabled.

No such bot.

   >?
  Commands:
 testcase1 or  testcase2 or testcase3
```

 
# 5.  GNU Readline Library
>Proposal.
Now, running ChatScript from linux terminal, standard behaviors of key arrows bash shell doesn't run; by example if I press an UP arrow keys to retrieve previous inserted  lines in a dialog I got:

 ^[[A^[[A^[[A^[[A^[[A
 
What I'd like is instead to retrieve "commands" history.

I think that's because function ReadALine() take a gectc()

I propose instead to use GNU readline library, allowing to retrieve previous statement (to re-edit user utterances); see: 
https://cnswww.cns.cwru.edu/php/chet/readline/readline.html
http://cnswww.cns.cwru.edu/php/chet/readline/rltop.html
https://cnswww.cns.cwru.edu/php/chet/readline/rluserman.html
http://stackoverflow.com/questions/6727171/using-readline-for-completion

thanks for your patience
respect
giorgio

**Comment by bwilcox-1234** [comment]
#1  the command line parameter is intended for build scripts. It should run to completion and exit.
My development process is to have CS running in local mode,  edit my files, give a :build command, test the bot, dont like something, edit the files, give a :build command, try it again (often via :retry). I don't generally leave the command window. If a compile error happens, I just press enter to return to normal command level, edit the files, do :build and continue as before.

**Comment by bwilcox-1234** [comment]
3 - the TOPIC folder only holds a single build. It is possible to build multiple bots within a single build (if your files are appropriately annotated) and then at the login message in local mode you can enter
bruce:harry   to select a specific bot.

**Comment by bwilcox-1234** [comment]
#4 using gnu would not work on windows. I'm reluctant to run separate support. But if you are just trying to reenter the most recent text you can do :retry,  and that puts you in the prior context as well. You can also try out alternatives in that prior context via :retry this is an alternate input.

**Comment by solyaris** [comment]
thx, some points clarified; btw unaware you was replying, I just modified / re-numbered my points...

**Comment by bwilcox-1234** [comment]
#2 - I'm not understanding the request. please rephrase.

**Comment by solyaris** [comment]
point 2 - i'ts possible to run the *:reset* as command line parameter?

    $  BINARIES/LinuxChatScript64 local login=giorgio bootcmd=reset

The above command do not make a reset (maybe I do not undertood meaning of "bootcmd") and [documentation](https://github.com/bwilcox-1234/ChatScript/blob/master/WIKI/ChatScript-System-Variables-and-Engine-defined-Concepts.md#execution-options) is not clear to me. 
thanks

**Comment by bwilcox-1234** [comment]
first, bootcmd would need to be bootcmd=:reset
Second, :reset is used to reset a user. When you are booting you do not yet know the user (despite login command param) because user login will occur later.  
But...  you could probably define a server variable and in your script check for that as well as start of conversation...
ChatScript login=giorgio Vreset=1

then in script
u: ( %input<%userfirstline $reset)  force a reset here

**Comment by solyaris** [comment]
* point 2
   Ah ok, thanks, in facts :reset matter just in test/debug phase, and I can input the command from the  shell-

* point 4
you say
>the TOPIC folder only holds a single build. It is possible to build multiple bots within a single build (if your  files are appropriately annotated) and then at the login message in local mode you can enter
> bruce:harry to select a specific bot.

I see. CS Multibot application feature is great (and underrated),
 
But let say you want to run on the same server MANY different CS bots applications (fully independents / not related), by example you have three different bots like:

* GiorgioBot - is a bot that chat emulating myself
* MyGrocery - is a conversational commerce / online shopping bout of company XYZ
* PIZZAHOT - is another different / unrelated ecommerce bot

What's the way to build/run all above with a CS server ?
I have to have CS separated directory tree ?

Sorry you maybe explained in documentation but  can't found info. Thanks again.

**Comment by bwilcox-1234** [comment]
Still have to build them in a single build. You have to compile all the files of all of them, but make sure you only have one "defaultbot" fact.  If they have conflicting facts or functions or topics, then you need to do a bot: command, which can now be done from the build script itself. For conflicting facts/functions, the botmacro will need to use $factowner=   and correspond to the bot: command used in the build script

**Comment by solyaris** [comment]
maybe an example in documentation could help a  lot :)

In case of an huge number of different unrelated bots (let say nr. 100 bots), a possible alternative could be to run each server bot on a different IP port and letting CS to read from different TOPIC folders; that make sense ?

**Comment by bwilcox-1234** [comment]
I will try to document the new stuff. You are limited to 64 completely independent bots.  CS is tied to a port and cannot flip ports on the fly. You can launch multiple instances of CS tied to different ports, but then that has nothing to do with running multiple bots from a single server.

**Comment by solyaris** [comment]
ok, If I understand correctly, I see two different scenarios:

1. **Multi-bot application** 
In this case, users talk with a **set** of ("cooperating") bots, that possibly share some data (share_xxx vars) and topics.
I do not have clear practical examples: maybe a game where user talk at the same time, with different bot-characters/bot-actors, or  an ecommerce marketplace bot platform, where each seller shop-bot share some logics (topics, etc.)
In these cases, is clear to me that a single **:build** if fine, because in facts the application is just one (single OS process responding on a single IP port).

2. **Different unrelated bots** (incidentally running on the same host)
Let's consider we want to run on the same machine very different unrelated bots for very different purpose: this is the case where I have a bot for ecommerce X, a bot for e-learning application Y, a bot character for game Z, etc. etc.
In this scenario I'd like to have fully separated CS code and related builds, and eventually different processes (one for each bot) also on different IP ports; 
Is this scenario possible with CS now, avoiding do clone all CS directory tree ? Do you already foresee this ?
BTW, this scenario is very important to run CS for business purpose, running on a same server multiple cs processes for differents purposes/customers...

Yes, maybe a specific documentation or new section about all this could very helpfull, thanks.

**Comment by ludan-av** [comment]
I'm into the same kind of questions.

Multi-bot application usecase is quite clear to me:
One specialized bot per usecase for a same company. I'd like to have separate control scripts for each bot. These multiple bots share and update the same user data.
I'd probably prefer to build them separately, but it's not an issue today.

Different unrelated bots:
That's what I presently do: I run them on the same server on different ports.
That's ok. Cloning the CS tree is not a real issue for me, even if I'd really prefer to have the engine data  completely separate from the all the bot data (that's why I asked for an external TOPIC folder parameter in the command line).
Still, in the long term, I might choose to have one server per bot (amazon EC2 nano). I'm not decided yet.

**Comment by solyaris** [comment]
Hi @ludan-av 

>That's what I presently do: I run them on the same server on different ports.
That's ok. Cloning the CS tree is not a real issue for me, even if I'd really prefer to have the engine data completely separate from the all the bot data 

in facts, in case of a lot of different bots,  cloning all seems to me a workaround solution, because the need to update N CS trees for every CS engine new release
 
>(that's why I asked for an external TOPIC folder parameter in the command line).

yes, maybe a solution is that CS engine run reading TOPIC/RAWDATA from command line params?

**Comment by ludan-av** [comment]
Hi @solyaris 
I agree. Eventually, it would be ideal to have:
1. a folder containing all the CS engine versions - I just unzip the new versions when they are available
2. a folder containing all the bot data (one per bot - RAWDATA TOPIC maybe also LIVEDATA?) - each bot with a parameter indicating which version they should use, and I switch them from one version to another when I decide

**Comment by solyaris** [comment]
> a folder containing all the CS engine versions - I just unzip the new versions when they are available

btw, I'd propose a `git pull` after an initial `git clone https://github.com/bwilcox-1234/ChatScript` :-)

**Comment by kuzyn** [comment]
That's getting out of scope, but I'd also be for a stricter separation of engine code & user/runtime data. This way and update could plausibly only involve a `git pull`

@solyaris some feedback:

1. 👎 Because we need to be able to compile and quit from the command line when scripting initializations and tests
5. 👍 Yes, yes, yes. The readline has been broken for OSX & Linux for a while, maybe even forever

**Comment by solyaris** [comment]
I apology because I submitted a mix of different points/proposals.
More guilty because I re-edite initial post after Bruce's answer creating myself possible confusion.
I close the issue and in case I'll reopen single points.

Multibot point is solved by Bruce release 7.x

> That's getting out of scope, but I'd also be for a stricter separation of engine code & user/runtime data. This way and update could plausibly only involve a git pull

I agree.

Regarding readline: I understand Bruce note. (to avoid #ifdef), nevertheless Linux+Mac are probably more used platforms for serious develop. The possibility to re-edit /  change previously submitted line  is useful to speed up dev/test. let say it's a "desiderata" :)

Thanks for your patience
