### ISSUE TITLE
deleting user data

### ISSUE THREAD

**Issue by whoisstan** [bwilcox-1234/ChatScript#49]
hi,

I am working with rob and mark btw ;) long time cs fan and user.

I am looking for ways of deleting user data:
-all conversations a certain bot ever had
-a specific conversation between a bot and a user, not :reset which is more like step 1, i like to go all the way to 0/empty.

if there isn't a command to run, are there files that can be deleted to achieve that? 

thanks,
stan

**Comment by hiteshsaraf** [comment]
"USERS" folder contains the log and historical conversations for all bots. You can empty this folder and it would be more like a step 0.

**Comment by bwilcox-1234** [comment]
CS7.4 5. erasename command parameter - full user reset if found in input
will start a user topic file from scratch BEFORE loading the user.
There is nothing to erase all conversations a bot ever had other than eraseing user folder content
