### ISSUE TITLE
RAWDATA command line parameters

### ISSUE THREAD

**Issue by ludan-av** [bwilcox-1234/ChatScript#54]
There's a recommended files organization in Installing-and-Updating-ChatScript - which is ok, but I'd prefer to have my own very personal files organization.

Thanks for the new command line parameters:
  livedata
  topic
  users
  logs

I have an issue with RAWDATA: I'd like to tell CS where to find my filesxxx.txt file(s).

In the doc:
  ChatScript automatically looks above itself to find your filesxxx.txt file if it can't find it within.

I'd prefer an extra command line parameter.

**Comment by bwilcox-1234** [comment]
next release  buildfiles=xxx for designating first search path to find your filesxxx
