### ISSUE TITLE
Files compilation order

### ISSUE THREAD

**Issue by jb-kerboeuf** [bwilcox-1234/ChatScript#57]
Hi,

I have noticed that the .top files are not compiled in the same order on Windows and other systems.
I have a file that needs to be compiled first because it contains some useful macros, so I named it 0macro.top . 

On Windows it works fine, but on Linux the files are not processed in alphabetical order. 

I've tried on Ubuntu 16.10 (local) and on an unknown linux distribution (server). The compilation order are different from alphabetical order, but also diffrent from each other, and surprisingly not random. Although I can't see any pattern, they're constant.

Is it a known issue ?

Thanks for your patience
JBK

**Comment by bwilcox-1234** [comment]
If you have a compilation order constraint, you should move the file out of the FOLDER and place it at the top level of your bot and name the order by where you request its compilation in the filesxxx.txt. For HARRY, that would mean creating a folder inside of HARRY, moving the existing files into that, then changing filesHarry.txt to reference the subfolder, and explicitly name a top level file you want to add to the harry folder
