### ISSUE TITLE
bug? input oob & languages

### ISSUE THREAD

**Issue by ludan-av** [bwilcox-1234/ChatScript#59]
I have oob in my input (json) and I am also playing around languages.

**With ENGLISH as a language:**

`$cs_token = #DO_ESSENTIALS`

In my control topic I have:
```
u: ( \[ _* ) # to catch input oob 
...

u: () # to catch text input
...
```

With an input like: `[ {} ] Toto`

It flows in the oob and then in the second u: - everything is fine.

 

**With language=FRENCH :**

(and exactly the same code)

It NEVER goes in the oob input section but directly in the second pattern.

PS: doesn't work neither with `u: (< \[ _* \])`

**Comment by bwilcox-1234** [comment]
This topic works fine for me when command parameter language=french is given and cs_token was do_essentials.
topic: ~INTRODUCTIONS keep repeat (~emogoodbye ~emohello ~emohowzit name here )
t: Welcome to?
u: ( \[ _* ) # to catch input oob 
u: () my input

**Comment by ludan-av** [comment]
My full standalone bot for this issue is:
```
outputmacro: test()

$cs_token = #DO_ESSENTIALS

$cs_control_main = ~controltest
$userprompt = ^"%user: >"
$botprompt = ^"test: "

table: defaultbot (^name)
^createfact(^name defaultbot defaultbot)
DATA:
test


topic: ~controltest system ()

u: ( \[ _* ) # to catch input oob
    ^log(OUTPUT_ECHO oob value is _0 \n)

u: ()
	^log(OUTPUT_ECHO in the main thing, processing: %originalsentence \n)
```


# With chatscript.exe port=1025

```
hello
=>
in the main thing, processing: hello
```

```
[ { with oob } ] hello
=>
oob value is {_with_oob_} ]
in the main thing, processing: [ { with oob } ]
in the main thing, processing: hello
```


# With chatscript.exe language=FRENCH port=1025

```
hello
=>
in the main thing, processing: hello
```
(ok)

```
hello
=>
in the main thing, processing: hello
in the main thing, processing: [ { with oob } ]
in the main thing, processing: hello
```
**there's no "oob value is"**

**Comment by ludan-av** [comment]
same issue on 7.2

**Comment by bwilcox-1234** [comment]
patched now in git.
