### ISSUE TITLE
Python's mystery issue (+ bot name case sensitivity)

### ISSUE THREAD

**Issue by solyaris** [bwilcox-1234/ChatScript#6]
Hi Bruce

I'm doing some tests with CS 6.7 under both:
- **Linux ubuntu server 14.04** 
  I git cloned this repo and I did a `make standalone` to use ChatScript with the interactive console.
- **Windows 10**
  I git cloned and I run chatscript.exe
  I just added the basic file pets.top under /RAWDATA/HARRY :

https://gist.github.com/solyaris/d7be913c865ec90da0995b943f071d7d

Before adding pets.top, both environments run HARRY bot worked as expected.
When I add pets.top file and I rebuild , I have two  issues on both Linux and Windows:
# Issue 1: bot name is case sensitive ?

On Linux even if i do a `:build harry` I can't see any change, it seems to me that the platform ignore the added file :( Instead on windows, the system appear to rebuild well pets.top but run only once ; 

```
ChatScript Version 6.7  compiled Jul 24 2016 10:56:47

>>Reading folder RAWDATA/HARRY/

----Reading file childhood.top
Reading topic ~childhood

----Reading file introductions.top
Reading topic ~introductions

----Reading file keywordless.top
Reading topic ~keywordless

----Reading file pets.top
Reading topic ~pets
*** Error- line 23 of pets.top: OUTPUT-3 Unbalanced )   in pets.top at 23: ?: ( << you like snake >>) I love pythons except Python \(the programming language\)

```

Ok, here the system report a syntax error, ok but afterward ChtaScript crash when runned again; now when I login with my name I got the error `no such bot` and the executable crash.

I discovered myself that when rebuilding, **the name of the bot is case sensitive**; 

if I submit commands:

`:build harry` 
`:reset giorgio` 

nothing happens. 

> Maybe could help a message error, something like: 
> 
> "harry bot directory not found"

The successful command to rebuild default bot is:

`:build Harry`

I was convinced that the  bot names was case insensitive: harry == Harry == HARRY).
in facts the document  [Writing a Chatbot.pdf](https://github.com/bwilcox-1234/ChatScript/blob/master/DOCUMENTATION/PAPERS/Paper-%20Writing%20a%20Chatbot.pdf), in chapter "Instant ChapScript", and document [Bot Harry - basic bot.pdf](https://github.com/bwilcox-1234/ChatScript/blob/master/DOCUMENTATION/PREDEFINED%20BOTS/Bot%20Harry%20-%20basic%20bot.pdf) both mention  `:build harry`. 
BTW, Maybe the documentation have to be corrected. 

> My modest suggestion: 
> I see the all capital letters name convention to name a directory containing a  bot ($HOME/Chatscript/HARRY) 
> so ... I propose to use a no-case-sensitive convention to refer to a bot name, in that way 
> :build harry == :build Harry == :build HARRY  :)

Anyway, having rebuilt the correct bot name (Harry), the new topic is processed correctly.

**Comment by solyaris** [comment]
I discovered by myself:

* when rebuilding, the name of the bot is case sensitive; the correct command to rebuild default bot is:

` :build Harry`

my fault (I was convinced that the  bot names was case insensitive: harry == Harry == HARRY).

```
giorgio: > :topicinfo ~pets

Topic: ~pets  Flags: Bot: all
  Seen: last gambit 7   last rejoinder 0  lastresponder

  Keys:
    dog                cat                pet                animal             bird               fish
  snake

Key Overlap: ~pets

  Rules:
  - 0(0) ?:  ( << you like snake >> ) I love pythons except Python ( the programming language )
    1(91) ?:  ( << you ~like ~animals >> ) I love all animals.
    2(148) t:  Do you have any pets?
       (1) a:  ( yes ) Great. You like animals.
       (2) a:  ( no ) You don't like animals?
       (3) a:  ( parrots ) Birds are nice.
       (4) a:  ( cat ) I prefer dogs
       (5) a:  ( [ parrot bird canary finch swallow ] ) Birds are nice.
  - 3(390) t:  I have a dog.
  gambits: 2  responders: 2 (?:0 s:2 u:0)  rejoinders: 5
HARRY:
giorgio: > :topicstats ~pets
    ~pets     gambits 2 responders 2 rejoinders 5 empties 0
Concepts 1860 Topics 1 rules 9 empties 0
  gambits 2  responders 2 (?: 2 s: 0  u: 0) rejoinders 5
HARRY:

```

A strange behaviour: 
```
giorgio: > do you like snakes?
HARRY:  I love pythons except (the programming language)

```

Why the output string omit the "Python" ?

**Comment by kuzyn** [comment]
Hey @solyaris, just wondering if you could still observe case 2 ? 

As for the `:build` capitalization issue, I _think_ that it might be dependent of the env. Windows is case insensitive, OSX and Linux isn't; my guess is that CS simply abide by its env when it tries to match the file. Also, as you might have deduced by now (since this issue was created a while ago), CS does't look for `/Chatscript/HARRY` when you do a build, but rather for `RAWDATA/filesHarry.txt` which bootstrap reading files in `/Chatscript/HARRY`

**Comment by solyaris** [comment]
Hi Samuel

1. capitalization
I was confused because, from an Ubuntu OS terminal, running  `:build harry`
this did NOT generate any error/complain. Immo it would generate an error, because there is not a  RAWDATA/fileharry.txt 
Also somewere in (old) documentation I read `:build harry` . Now,  [here](https://github.com/bwilcox-1234/ChatScript/blob/master/WIKI/PREDEFINED-BOTS/Bot-Harry.md) is correct.

2. Python...

I just retried: 

- I downloaded last CS release 7.111

- I added the file pets.top in RAWDATA/HARRY/pets.top :

```
topic: ~pets (dog cat pet animal bird fish snake)

?: ( << you like snake >>)
   I love pythons except Python (the programming language)

?: ( << you ~like ~animals >>) 
   I love all animals.

t: Do you have any pets?
  #! yes
  a: ( yes) Great. You like animals.

  #! no
  a: (no) You don't like animals?

  #! I have two parrots
  a: (parrots) Birds are nice.

  #! I have a cat
  a: (cat) I prefer dogs

  #! I have a canary
  a: ([parrot bird canary finch swallow]) Birds are nice.

t: I have a dog.

```

- I rebuild 

but unfortunately I got the same Python" word omission:

```
# BINARIES/LinuxChatScript64 local
CommandLine:
    local

ChatScript EVSERVER Version 7.111 pid: 9019 64 bit LINUX compiled Jan 16 2017 04:54:53 host=local
Params:   dict:2097151 fact:800000 text:100000kb hash:100000
          buffer:80x80kb cache:1x5000kb userfacts:100 outputlimit:80000 loglimit:80000
WordNet: dict=214033  fact=85706  heap=12701684 Jan15'17-12:54:50
Build0:  dict=67756  fact=130446  heap=1146016 Compiled:Nov19'16-15:54:10 by version 6.9 "0"
Build1:  dict=167  fact=15  heap=211788 Compiled:Nov20'16-08:26:03 by version 6.9 "harry"
Used 60MB: dict 281,957 (24812kb) hashdepth 14/1 fact 216,167 (10376kb) heap 14182kb
           buffer (6400kb) cache (5000kb) POS: 918 (29kb)
Free 113MB: dict 1,815,194 hash 13580 fact 583,833 stack/heap 85,817KB

    Dictionary building disabled.


Enter user name: giorgio

mkdir: cannot create directory ‘USERS’: File exists
HARRY:  Welcome to ChatScript.
giorgio: > :build Harry
ChatScript Version 7.111  compiled Jan 16 2017 04:54:53

>>Reading folder RAWDATA/HARRY/

----Reading file keywordless.top
Reading topic ~keywordless

----Reading file simplecontrol.top
Reading outputmacro: ^harry
Reading table tbl:defaultbot
    Locals: ^name,
Reading topic ~control
*** Warning- line 26 of simplecontrol.top: loopback is not a known word. Is it misspelled?
Reading topic ~xpostprocess

----Reading file introductions.top
Reading topic ~introductions

----Reading file childhood.top
Reading topic ~childhood

----Reading file pets.top
Reading topic ~pets

<<end folder RAWDATA/HARRY

>>Reading folder RAWDATA/QUIBBLE/

----Reading file eliza_when.top
Reading topic ~quibble_when

----Reading file quibble.top
Reading topic ~quibble_all

----Reading file eliza_who.top
Reading topic ~quibble_who

----Reading file eliza_misc.top
Reading topic ~quibble_misc
*** Warning- line 400 of eliza_misc.top: shoulds is not a known word. Is it misspelled?

----Reading file eliza_because.top
Reading topic ~quibble_because

----Reading file eliza_where.top
Reading topic ~quibble_where

----Reading file eliza_do.top
Reading topic ~quibble_do

----Reading file eliza_can.top
Reading topic ~quibble_will
Reading topic ~quibble_can

----Reading file honest.top
Reading topic ~intent
Reading topic ~honest_response

----Reading file eliza_how.top
Reading topic ~quibble_howmuch
Reading topic ~quibble_how

----Reading file eliza_what.top
Reading topic ~quibble_what

----Reading file eliza_not.top
Reading topic ~quibble_not

----Reading file eliza_or.top
Reading topic ~quibble_or

----Reading file eliza_why.top
Reading topic ~quibble_why

<<end folder RAWDATA/QUIBBLE

WARNING SUMMARY:
0 serious warnings, 0 function warnings, 2 spelling warnings, 0 case warnings, 0 substitution warnings


Finished compile

ChatScript EVSERVER Version 7.111 pid: 9019 64 bit LINUX compiled Jan 16 2017 04:54:53 host=local
Params:   dict:2097151 fact:800000 text:100000kb hash:100000
          buffer:80x80kb cache:1x5000kb userfacts:100 outputlimit:80000 loglimit:80000
WordNet: dict=214033  fact=85706  heap=12701684 Jan15'17-12:54:50
Build0:  dict=67756  fact=130446  heap=1146016 Compiled:Nov19'16-15:54:10 by version 6.9 "0"
Build1:  dict=169  fact=22  heap=212352 Compiled:Jan16'17-16:17:11 by version 7.111 "Harry"
Used 60MB: dict 281,959 (24812kb) hashdepth 14/1 fact 216,174 (10376kb) heap 14183kb
           buffer (6400kb) cache (5000kb) POS: 918 (29kb)
Free 113MB: dict 1,815,192 hash 13580 fact 583,826 stack/heap 85,816KB

    Dictionary building disabled.


HARRY:  Have you been here before?
giorgio: > yes
HARRY:  Do you have any pets?
giorgio: >  do you like snakes?
HARRY:  I love pythons except (the programming language)
giorgio: > :why
~pets.0.0.2.9.0  ?:  ( << you like snake >> ) I love pythons except Python ( the programming language )
 via ~control.2.9.0  u:  ( ) $$currenttopic = %topic ^if 00m( %response  0 ) 00I{ ^nofail ( TOPIC ^rejoinder ( ) ...
HARRY:
giorgio: >

```

Any idea ?

Thanks
giorgio

**Comment by kuzyn** [comment]
Replicated with other uppercase names (Delphi, Javascript) ... seems to be linked to how the `~propername` concept is assembled

**Comment by solyaris** [comment]
thx @kuzyn 

btw I tried to use active strings:

    ?: ( << you like snake >>)
       I love pythons except ^"Python" (the programming language)

here I have a new problem: a double blank char before Python; see below the output:

    giorgio: > do you like snakes?
    HARRY:  I love pythons except  Python (the programming language)

**Comment by solyaris** [comment]
Bruce, the double blanks with active string here above, is maybe related to the bug you mentioned in "blanks incomprehensions" issue, see #47 ? thanks

**Comment by bwilcox-1234** [comment]
Unrelated. Different bug. Also fixed for new release.
