### ISSUE TITLE
Issues running on mac

### ISSUE THREAD

**Issue by arashsa** [bwilcox-1234/ChatScript#61]
When I try to run on mac I get this issue:

```
dyld: Library not loaded: /usr/local/lib/libbson-1.0.0.dylib
  Referenced from: /Users/arashsaidi/Work/ConverTelligence/DnB/ChatScript/BINARIES/./MacChatScript
  Reason: image not found
[1]    30267 abort      ./MacChatScript local
```

**Comment by kuzyn** [comment]
You'll need to install the mongo drivers locally either by following [these instructions](http://mongoc.org/libbson/1.3.5/installing.html) or by installing them through homebrew

**Comment by tkuebler** [comment]
there is also:  https://github.com/bwilcox-1234/ChatScript/blob/master/WIKI/OVERVIEWS-AND-TUTORIALS/ChatScript-on-a-Mac.md
