### ISSUE TITLE
utf-8 and capital letters

### ISSUE THREAD

**Issue by jb-kerboeuf** [bwilcox-1234/ChatScript#62]
Hi. 
ChatScript doesn't know how to deal with all special letters in utf-8.

1. There is no match between a special letter and its capital. For example é and É
2. There is no match between a special letter and its regular form. For example ñ and n
```
u: (light)
# => matches "LIGHT"
u: (éclair)
# => doesn't match "ÉCLAIR"
u: (sœur)
# => doesn't match "soeur"
```

Note : the relation in 2. is not symmetric... 
'é' should match 'e' , 'E' and 'É' 
but 'e' shouldn't match 'é'

Here is a list if it helps : 

À à
Á á
Â â
Ã ã
Ä ä
Å å
Ą ą
Ă ă
Æ æ
Ç ç
Ć ć
Č č
Ď ď
Ð ð
È è
É é
Ê ê
Ë ë
Ę ę
Ě ě
Ğ ğ
Ì ì
Í í
Î î
Ï ï
Ł ł
Ñ ñ
Ń ń
Ň ň
Ò ò
Ó ó
Ô ô
Õ õ
Ö ö
Ő ő
Ø ø
Œ œ
Ř ř
Ś ś
Š š
Ş ş
Ţ ţ
Ť ť
Ù ù
Ú ú
Û û
Ü ü
Ű ű
Ů ů
Ŵ ŵ
Ÿ ÿ
Ý ý
Ŷ ŷ
Ź ź
Ż ż
Ž ž
Þ þ

Thank you.

**Comment by bwilcox-1234** [comment]
True. thanks. Next version will match up upper and lower case forms.

**Comment by jb-kerboeuf** [comment]
Thanks ! 

But point 2 is also critical, especially for spellcheck.
I have updated the list for this point : 

à a
á a
â a
ã a
ä a
å a
ą a
ă a
æ ae
ç c
ć c
č c
ď d
ð d
è e
é e
ê e
ë e
ę e
ě e
ğ g
ì i
í i
î i
ï i
ł l
ñ n
ń n
ň n
ò o
ó o
ô o
õ o
ö o
ő o
ø o
œ oe
ř r
ś s
š s
ş s
ţ t
ť t
ù u
ú u
û u
ü u
ű u
ů u
ŵ w
ÿ y
ý y
ŷ y
ź z
ż z
ž z

**Comment by bwilcox-1234** [comment]
not disagreeing. just havent reviewed what exactly I will be doing there. Thanks for the list

**Comment by bwilcox-1234** [comment]
I have fixed spellcheck to go either way, from any accented char to its unaccented base for or visa versa

**Comment by jb-kerboeuf** [comment]
```
:prepare DÉLIVRÉ

Original User Input: DÉLIVRÉ
Tokenized into: DÉLIVRÉ
Spelling changed into: délivre
```

There's an issue here. Should be "délivré" not "délivre"

**Comment by bwilcox-1234** [comment]
So, currently the french dictionary has  délivre ( VERB_PRESENT VERB_PRESENT_3PS NOUN VERB NOUN_SINGULAR )  in addition to your one with ending accented e and the spell check algorithm charges nothing for flipping accents on and off.

**Comment by bwilcox-1234** [comment]
OK> checked in a fix to spellcheck to handle the issue. see if that is what you need
