### ISSUE TITLE
^join is adding spaces between arguments without AUTOSPACE

### ISSUE THREAD

**Issue by juanmirod** [bwilcox-1234/ChatScript#63]
Hi, I am trying to join a phone number like this:

```
u: ( send sms {to} _~number _~number _~number _* ) ^keep() ^repeat()
   $$phone = ^join('_0 '_1 '_2)
   $$message = ^original(_3)
   /sms ^print(OUTPUT_NOCOMMANUMBER $$phone) $$message
```

But I get the number with spaces between the three numbers:

```
> send sms to 600 123 123 Hi
HARRY:  /sms 600 123 123 Hi
```

I have also tried `^join(^original('_0) ^original('_1) ^original('_2))` with the same result. I don't know if I am missing something about the behavior of join with numbers but I though that not using AUTOSPACE should concatenate the arguments as one string.

UPDATE:
If I use this rule:
```
u: ( _~number _~number _~number ) ^keep() ^repeat()
   $$phone = ^join('_0 '_1 '_2)
   The phone number is ^print(OUTPUT_NOCOMMANUMBER $$phone)
```
I get the expected result:
```
> 600 123 123
HARRY:  The phone number is 600123123
```

**Comment by bwilcox-1234** [comment]
When I do this:
u: (buy) $x = 500  $y = 400 $z = 333
$xx = ^join($x $y $z)
$xx
I get 500,400,333  (because I have not changed output control to not put commas in numbers.
What do you get and what version of CS are you using?

**Comment by juanmirod** [comment]
I get `500,400,333` too, I am using version 7.111 It's a strange behaviour because If I remove some words before the numbers it works:

```
# This returns /sms 500400333
u: ( send _~number _~number _~number _* ) ^keep() ^repeat()
   $$phone = ^join('_0 '_1 '_2)
   $$message = ^original(_3)
   /sms ^print(OUTPUT_NOCOMMANUMBER $$phone) $$message
```

But If I add more than 1 word before the numbers in the pattern I get the spaces back:
```
# This returns /sms 500 400 333
u: ( send sms _~number _~number _~number _* ) ^keep() ^repeat()
   $$phone = ^join('_0 '_1 '_2)
   $$message = ^original(_3)
   /sms ^print(OUTPUT_NOCOMMANUMBER $$phone) $$message
```

Could I be hitting some kind of limit in the pattern? Is there a better way to do this?

**Comment by juanmirod** [comment]
Ok, I found the issue thanks to :trace. Thanks for all those dev tools built into ChatScript ;)

The problem was that I was hitting another rule that was like `u: ( send sms _~number _* )` And this was making `_0 = 500` and `_1 = 400 333` I still don't quite understand why `500 400 333` instead of `500400 333` but this is definitely the rule creating the unexpected output. 

Thanks again Bill, and sorry for submitting an issue that was not a bug, sometimes you only need to state your problem to make the solution appear in front of you.
