### ISSUE TITLE
No such bot when running CS as a service

### ISSUE THREAD

**Issue by smartapant** [bwilcox-1234/ChatScript#7]
Hi Bruce!
I am currently building my client to play with CS and ran into an issue. 
When i run LinuxChatScript64 and set up a client everrything is ok, i connect to bot Harry and have a chat with him. 
The problem happens when i configure chatscript service in init.d and run it as a service. From my client i connect it successfully but it says 'no such bot' all the time. 

I hope i'm just missing some chatscript configuration details :)

**Comment by bwilcox-1234** [comment]
Cant tell you much about how you are running it as a service.  ChatScript protocol is to receive a transient tcp connection and be sent 3 C strings jammed together- username, botname or empty string, user message or empty string.  CS then sends back response and closes the connection.  You may be better advised to post on the ChatScript forum on Chatbots.org, as users there may be able to guide you

**Comment by smartapant** [comment]
@bwilcox-1234 thanks for your response! i start ChatScript in server mode and send it messages in the format you described, the problems start when i run it in background. Might be some child mistake there, i will try to solve it and if it will be important enough, i will describe the solution here

**Comment by kuzyn** [comment]
Can you post your service here (if it's custom) or how you instantiate CS? And what kind of parameters are you passing to it & are you sure you can reach your server?
