### ISSUE TITLE
French tokenization

### ISSUE THREAD

**Issue by ludan-av** [bwilcox-1234/ChatScript#70]
French tokenization has to manage apostrophes, which are quite common. There are 2 cases:
- "aujourd'hui" (today) is in the dict, we don't want to split on apos here.
- "n'irait" (won't go) needs to be split in n' + irait. n' will be further replaced by "ne" via substitutes.

There's already a mechanism for that for French in the code. "j'étais" and "t'appelle" are well split.
But n' doesn't.

We think that this is the complete list:
c'
d'
j'
m'
n'
s'
t'
qu'
puisqu'
lorsqu'
cht'

one-letter ones are easy to add in the code. A little more difficult for the other ones.

@bwilcox-1234 
We can make the changes in the code and do a pull request. Is it ok for you?
Or do you prefer to do the changes directly?
Tell us.

**Comment by bwilcox-1234** [comment]
free free to generate a pull request and I'll review it.

**Comment by jb-kerboeuf** [comment]
A few hours ago I did a pull request that does exactly this. :)

**Comment by bwilcox-1234** [comment]
Not an expert using git ,  but I dont see any pull requests pending (top line says pull-requests 0) and I dont have an email notification that I noticed

**Comment by jb-kerboeuf** [comment]
hmmm I did not see it coming but there still is an issue when everything's in capslock.

```
:prepare j'aime

Original User Input: j'aime
Tokenized into: j'  aime
Substituted (contractions ) into: je  aime
Actual used input: je(j') aime
```

```
:prepare J'AIME

Original User Input: J'AIME
Tokenized into: J'AIME
Actual used input: J'AIME
```

Should I add the capital letters in the code I pushed for this issue?
Or would it be smarter to procede otherwise?

**Comment by bwilcox-1234** [comment]
if this is still an issue in 7.31, change and request merge.
