### ISSUE TITLE
How can ChatScript be build for Android?

### ISSUE THREAD

**Issue by AmlanDwivedy** [bwilcox-1234/ChatScript#71]
I have 2 questions
   1.How to build this project to run on Android.
   2. How to train with custom data in that process?

Thanks in Advance
Amlan.

**Comment by mrodriguez711** [comment]
I have the same question. Thanks

**Comment by solyaris** [comment]
Hi 

> 2. How to train with custom data in that process?

* what do you mean with "train" ?
* what do you mean with "custom data" ?

**Comment by AmlanDwivedy** [comment]
Can I feed with data for custom response? If yes how?

**Comment by AmlanDwivedy** [comment]
Lets say i am building a chatbot for custom service for company X.

It should say "Welcome to company X"
And Its responses should be around company X products .

Can it be done?

**Comment by bwilcox-1234** [comment]
It can be done. Responses are whatever you write for gambits and rejoinders in your chatbot. the startup message from Harry is in ~introductions topic and you can edit it to whatever you want
