### ISSUE TITLE
blank is missing before a match variable in output

### ISSUE THREAD

**Issue by solyaris** [bwilcox-1234/ChatScript#78]
Hi! 
a strange behavior, using: ChatScript EVSERVER Version 7.12 pid: 19212 64 bit LINUX compiled Jan 28 2017 19:52:55 host=local

Let's consider this topic (pets.top):

```
topic: ~pets (dog cat pet animal bird fish snake ~food)

?: ( << you like snake >>)
   I love pythons except ^"Python" (the programming language)

?: ( << you ~like ~animals >>)
   I love all animals.

?: RULE1 (do you eat _[ ham eggs bacon]) I eat '_0.

t: Do you have any pets?
   a: ( ~yes ) What kind of pet?

     b: (dog) I like dogs me too, Do you like big ones ?

        c: (~yes) I own a bulldozer.
        c: (~no) A dachshunds lover you too?

     b: (cat) I prefer dogs.
     b: (~animals) are you an animal rights activist?
     b: RULE2 (_*) hey! we are talking about pets, not about _0.

  a: (~no) You don't like animals?

t: I have a dog.
```

See this conversation chunk:
```
giorgio: > do you eat eggs?
HARRY:  I eateggs.
giorgio: >
HARRY:  Do you have any pets?
giorgio: > yes
HARRY:  What kind of pet?
giorgio: > bananas
HARRY:  hey! we are talking about pets, not about banana.
giorgio: >
```

the problem is in rule RULE1
```
?: RULE1 (do you eat _[ ham eggs bacon]) I eat '_0.
```
giving:
```
giorgio: > do you eat eggs?
HARRY:  I eateggs.
```

I would expect a blank char after _I eat_, as specified in the output statement  `I eat '_0.`, where I'd like to print out the _original_ form of match variable. 

    HARRY:  I eat eggs.

Instead I got this:

    HARRY:  I eateggs.

__So the BLANK character is omitted.__
__Why ? It's a bug or I misunderstood something about match variables?__

BTW, the RULE2, where I used the _canonical_ form of match variable (`_0`) 

     b: RULE2 (_*) hey! we are talking about pets, not about _0.

gives the expected output:

    HARRY:  What kind of pet?
    giorgio: > bananas
    HARRY:  hey! we are talking about pets, not about banana.

thanks

**Comment by solyaris** [comment]
update:

- incidentally I installed **ChatScript version 7.3** on a Macintosh, realizing the problem  did not come up with MacChatScript.
- I'll verify on Linux

Maybe a problem solved on new CS release.

**Comment by bwilcox-1234** [comment]
Presumably it is. I never see this bug but there may have been a point where spacing bug occured when altering output to handle french.
