### ISSUE TITLE
Handling multiple sentences.

### ISSUE THREAD

**Issue by unsigned6** [bwilcox-1234/ChatScript#80]
Hi. I've got a topic which describe set of phrases, one of which is question of such type:

`topic: ~main repeat keep []`

`u: QUESTION_ABOUT_TERM (what * if you ["go away" "get acquired" "go public"])`
`    ^respond(~specific_questions)`

And questions like "What happens if you go away?" or "What if you get acquired or go public?" are matched by this pattern. But if I send each of them with some sentence before ("Okay, it's great. What if you get acquired or go public?"), rule did not work.
It seems ChatScript search matches only in first sentence of input.

Is any possibility to match such kind of inputs? I tried adding to rule set of first words like this:
`([". what" what] * if you ["go away" "get acquired" "go public"]` 
but it did not have needed effect.

**Comment by bwilcox-1234** [comment]
Your new input consists of 3 sentences- Okay      it's great.    What if you ....
So if you have NOT already generated output from the 1st 2 sentences, CS would match the 3rd. But the simple harry control script only runs til it matches one input. I don't know that you want to match every input and say something for each.

**Comment by unsigned6** [comment]
Thanks for response. Actually I'm using simple control script from Harry chatbot. But even it did not match when there is nothing to match in first sentence. Basically what I want - to search for matches in all sentences of input and return only that match which was found first.
So if I have input "Okay, it's great. What if you get acquired or go public?" and rule match with the second sentence of it, i need make respond to ~specific_questions .
Could you please suggest how can I modify Harry's simple control to search matches not only in first sentence of input?

**Comment by solyaris** [comment]
@unsigned6  
Yurii, I feel this is not an issue (but a frequent asked question :-) ); This maybe could help: https://www.chatbots.org/ai_zone/viewthread/1822/#18612

@bwilcox-1234 
Because the FAQ (control script to process multiple sentence in queue)
maybe could be great to update the control script wiki doc: https://github.com/bwilcox-1234/ChatScript/blob/master/WIKI/ESOTERIC-CHATSCRIPT/ChatScript-Control-Scripts.md with an explicit code; that's would very helpfull!

**Comment by unsigned6** [comment]
@solyaris
thanks for your answer, thread was really helpful. Agree that this is not an issue and closing it. Also confirm that it would be great to update wiki documentation.
