### ISSUE TITLE
numbers in other languages

### ISSUE THREAD

**Issue by jb-kerboeuf** [bwilcox-1234/ChatScript#81]
Hello !
I made some changes on a fork, I'll make a pull request once I'm sure it works, but for now I have an issue.

in textUtilities.cpp there is this table : 

```
NUMBERDECODE numberValues[] = { 
 { (char*)"zero",0,4,REALNUMBER}, { (char*)"zilch",0,5,0},
 { (char*)"one",1,3,REALNUMBER},{ (char*)"first",1,5},{ (char*)"once",1,4,0},{ (char*)"ace",1,3,0},{ (char*)"uno",1,3,0},
...
}
```
So I added mine : 
```
NUMBERDECODE numberValuesFrench[] = { 
 { (char*)"zéro",0,4,REALNUMBER}, { (char*)"zero",0,4,REALNUMBER},
 { (char*)"un",1,2,REALNUMBER}, { (char*)"une",1,3}, { (char*)"premier",1,7}, { (char*)"première",1,8},
...
}
```

and then farther in the code there is : 
```
	if (!hasDigit) for (unsigned int i = 0; i < sizeof(numberValues)/sizeof(NUMBERDECODE); ++i)
    {
        if (len == numberValues[i].length && !strnicmp(word,numberValues[i].word,len)) 
		{
			return numberValues[i].value;  // a match (but may be a fraction number)
		}
    }
```

which I changed to be language specific : (it's the same code twice, only the variable numberValuesFrench changes)
```
	if (!stricmp(language, "english") && !hasDigit) for (unsigned int i = 0; i < sizeof(numberValues)/sizeof(NUMBERDECODE); ++i)
    {
        if (len == numberValues[i].length && !strnicmp(word,numberValues[i].word,len)) 
		{
			return numberValues[i].value;  // a match (but may be a fraction number)
		}
    }
    else if (!stricmp(language, "french") && !hasDigit) for (unsigned int i = 0; i < sizeof(numberValuesFrench)/sizeof(NUMBERDECODE); ++i)
    {
        if (len == numberValuesFrench[i].length && !strnicmp(word,numberValuesFrench[i].word,len)) 
		{
			return numberValuesFrench[i].value;  // a match (but may be a fraction number)
		}
    }
```

But for a mysterious reason CS just ignores it completly. It works for english, but if I run CS in french I don't get the canonical form.

in english (with interverted tables) : 
```
:prepare soixante-sept

1: soixante-sept (raw):  +~noun +~adjective +~adjective_number +~noun_number +~noun_bits +~number +soixante-sept //
1: 67 (canonical):  +67 //   +~integer +~positiveInteger  +-sept +soixante-
```

in french : 
```
:prepare soixante-sept

1: soixante-sept (raw):  +soixante-sept //
1: soixante-sept (canonical):  //   +-sept +soixante-
```

Do you know why it works that way ?
Thanks !

**Comment by bwilcox-1234** [comment]
probably because getting the canonical value of a word is done in the "pos-tagger" code  GetPosData, which is english specific and therefore only invoked for english. For other languages, if one is using an external pos-tagger, that would be responsible for generating the canonical form, but of course nobody else's pos-tagger would generate the digit form of a text number as a canonical form. Nominally, one would have to write an equivalent of GetPosData for the foreign language and put it in private code. Though currently there is no indirection mechanism for calling it.  I might be able to provide that.

**Comment by jb-kerboeuf** [comment]
With 7.31, putting the numbers in livedata made it a lot cleaner and easier to edit, but Chatscript still doesn't take the canonical form. 

So now soixante-sept is flagged as a number -nice- but it is useless if I can't know the value.

for example if I say "soixante-sept" and try this : 
```
u: (_~number)
    _0 + 1
```
It matches, but returns 1. Because it tries to do "soixante-sept"+1...

I made a little workaround to do what I wanted, but the fact that the canonical form is tied to the tagger is getting realy annoying. There is canonical forms everywhere, from the livedata to the dict, and no simple way to just read it ?

**Comment by bwilcox-1234** [comment]
The next improvement will separate out the numbers data from the english postagging code, so numbers.txt will take effect regardless of postagging.

**Comment by jb-kerboeuf** [comment]
Ok thanks ! 
This will be greatly appreciated :)

**Comment by jb-kerboeuf** [comment]
For now, as I said, I did a little algorithm in my bot that does the interpretation of numbers, so here it is: 

```
table: Nombres (^lettres ^chiffres ^type)
	^createfact(^lettres correspond ^chiffres)
	^createfact(^lettres deType ^type)
	DATA:
	zéro	0 REAL_NUMBER 
	un	1	REAL_NUMBER 
	deux	2	REAL_NUMBER 
# ... etc. Just copy/paste the numbers.txt in the table

# gets the int from the table
outputmacro: ^correspondNb(^nbLettres)
	@1 = ^query(direct_sv ^nbLettres correspond ?)
	@1object

# parses correctly the number, for example "mille neuf cent soixante sept"
# litteraly "one thousand nine hundred sixty seven"
# returns 1967
# it's simplistic and doesn't work for decimals and fraction numbers.
outputmacro: ^traiterNombre(^nombre)
	$_i = 0
	$_tmp = 0
	@0 = ^burst(^nombre "-")
	^loop(@0) {
		$_i += 1
		$_n = ^nth(@0 $_i)
		$_last = ^extract($_n -1 +1)
		if($_last==s AND $_n!=trois AND $_n!=tiers) {
			$_fin = ^length($_n) - 1
			$_n = ^extract($_n 0 $_fin)
		}
		$_nInt = ^correspondNb($_n)
		if($_i == 1) {
			if($_nInt == null ) { 
				$_result = ^substitute(character ^nombre "-" "") 
				^end(loop)
			}
			$_result = $_nInt
		}
		else {
			if($_nInt == null ) {
				if($_n == 000) { $_nInt = 1000 }
				else { $_nInt = 0 }
			}
			if($_result <= $_nInt) { $_result *= $_nInt }
			else if($_tmp == 0) { $_tmp = $_nInt }
			else if($_tmp <= $_nInt) { $_tmp *= $_nInt }
			else {
				$_result += $_tmp
				$_tmp = $_nInt
			}
		}
	}
	$_result += $_tmp
	$_result
```

It works, but I have to call the macro each time I match a ~number to understand it.

If you'd like some help on the next improvement you're talking about, I'd be glad to. Just need some guidance to find the bits of code to edit.

**Comment by bwilcox-1234** [comment]
I pushed a commit "fixing numbers". See how that works for you.

**Comment by solyaris** [comment]
Hi @jb-kerboeuf  

off-topic: great code/ CS script usage understanding. If you have time/mind to help improve this repo WIKI documentation, may you would help (me) to show some code snippets in docs ? 
Can I contact you via mail (my mail: giorgio.robino@gmail.com). 

Thanks
giorgio
