### ISSUE TITLE
minor - :commands output broken (in client-server mode)

### ISSUE THREAD

**Issue by solyaris** [bwilcox-1234/ChatScript#83]
Hi Bruce, 

I'm working on a linux client wrapper (sort of CS botdev tool)  I discovered a minor issue in _client-server_ mode: 
 
`:commands` do not report the list of CS commands, but say 

    use one of those as all input.

expected output is instead, that one correctly supplied in _standalone_ mode:

```
   >>:commands

---- Debugging commands -
:do - Execute the arguments as an output stream, e.g., invoke a function, set variables, etc
:silent - toggle silent - dont show outputs
:log - dump message into log file
:noreact - Disable replying to input
:notime - Toggle notiming during this topic
:notrace - Toggle notracing during this topic
:redo - Back up to turn n and try replacement user input
:retry - Back up and try replacement user input or just redo last sentence
:say - Make chatbot say this line
:skip - Erase next n gambits
:show - All, Input, Mark, Number, Pos, Stats, Topic, Topics, Why, Reject, Newlines
:time - Set timing variable (all none prepare match ruleflow pattern query json macro user usercache sql tcp topic)
:trace - Set trace variable (all none basic prepare match output pattern infer query substitute hierarchy fact control topic pos)
:why - Show rules causing most recent output
:authorize - Flip authorization for all debug commands

...
...
```

Maybe just an erratum.  See:

    >> :prepare do you eat bacon?

    eat     Object: bacon ? (char*) PRESENT

    >> :topicinfo

    > ) ^keep ( ) ^gambit ( $$currenttopic )

     >> :commands

    use one of those as all input.

modest proposal:

:commands are a really powerful CS feature for bot makers test/debug and those deserve a better usage explanation (in documentation) :-) 

The wiki document that detail the syntax of each command could be enhanced:
https://github.com/bwilcox-1234/ChatScript/blob/master/WIKI/ChatScript-Debugging-Manual.md

I'd suggest, for each command, to explain one or more small **parameters usage examples**.

On low priority, it could be helpfull to have an online help, something like like

    >>:help topicinfo
    
    blablabla
    blablabla

Thanks for your patience! 
**CS commands directives are great!**
giorgio

**Comment by bwilcox-1234** [comment]
in current version linux/windows I do not see a problem seeing :commands displayed as a client of a server

**Comment by bwilcox-1234** [comment]
>> :prepare do you eat bacon?  -- fixed (later version)

**Comment by bwilcox-1234** [comment]
:topicinfo -- not seeing anything displaying incorrectly.

**Comment by solyaris** [comment]
hi Bruce

using client-server, is all fine with :* commands except with `:commands`:

I run the server:
```
$ nohup sh -c 'cd /my home/ChatScript/BINARIES && ./LinuxChatScript64 port=1024' >/dev/null 2>&1 &
```

so I run the client using a TCP socket connection with my Ruby code here: https://github.com/solyaris/rChatScript/ 
 
If run  `:commands`: I got 

```
>> :commands

use one of those as all input.
 ```

the string is not expected output ?!

 ```
$ grep -nr 'use one of those as all input.' .

...
...
./SRC/testing.cpp:9770: { (char*)":autoreply",C_AutoReply,(char*)"[OK,Why] use one of those as all input."},
 ```

Nevertheless,  if I run:
```
$ nc localhost 1024
testuser^@giorgiobot^@:commands^@
 ```

I got the expected output list

 ```
---- Debugging commands -
:do - Execute the arguments as an output stream, e.g., invoke a function, set variables, etc
:silent - toggle silent - dont show outputs
:log - dump message into log file
:noreact - Disable replying to input
:notime - Toggle notiming during this topic
:notrace - Toggle notracing during this topic
:redo - Back up to turn n and try replacement user input
:retry - Back up and try replacement user input or just redo last sentence
:say - Make chatbot say this line
:skip - Erase next n gambits
:show - All, Input, Mark, Number, Pos, Stats, Topic, Topics, Why, Reject, Newlines
:time - Set timing variable (all none prepare match ruleflow pattern query json macro user usercache sql tcp topic)
:trace - Set trace variable (all none basic prepare match output pattern infer query substitute hierarchy fact control topic pos)
:why - Show rules causing most recent output
:authorize - Flip authorization for all debug commands

---- Fact info -
...
 ```

Confused.
I close myself the issue and I'll reopen, in case
