### ISSUE TITLE
Unable to use Postgres as a replacement for the local file system of the USERS directory.

### ISSUE THREAD

**Issue by unsigned6** [bwilcox-1234/ChatScript#88]
Hi. I was trying to go through manual [ChatScript PostgreSQL](https://github.com/bwilcox-1234/ChatScript/blob/master/WIKI/ESOTERIC-CHATSCRIPT/ChatScript-PostgreSQL.md).

And for me database users and table userfiles is not creating.
What I've done:
executed in terminal
` pguser="hostaddr = 127.0.0.1 port = 5432 user = postgres " `
than in the same shell run chatscript binary
` ./BINARIES/LinuxChatScript64 local `
after sending few messages to my chatbot data is still writing to file in USERS folder, but there was no any corresponding tables in  postgres database. I was trying it both on Ubuntu 16.04 and Centos 7 (installed on centos with instructions you've given).
Also i tried to set password to postgres user in database and set `pguser` with password param, but still no effect. I've checked in postgres database:
```
postgres=# \dt
No relations found.
postgres=# \c users
FATAL:  database "users" does not exist
Previous connection kept
```
Can you give me a hint what I could miss? Thanks.

**Comment by bwilcox-1234** [comment]
std linux cs release does not have postgres. You need to "make pgserver" in SRC directory.

**Comment by unsigned6** [comment]
Thanks for answer. I've made build and tried again with new CS binary for postgres but still don't have storing data from USERS in database. Btw, I tried with this new binary your postgres chatbot and it actually has connection with DB - i was able to connect, create table. Here is credentials which I used in ^dbinit:

`u: (open)  if (^dbinit( dbname = postgres port = 5432 user = postgres password = somepassword  )) {db opened}`

as a result connection is really working ():

```
POSTGRES:  Ready- type: open, table, tables, store, list, drop, or close
test: > open
POSTGRES:  Db opened
test: > table
POSTGRES:  Table s created
test: > store
POSTGRES:  Completed
test: > list
POSTGRES:  1
 Completed
```
and this is what I set to pguser variable (in bash) before starting CS:

`pguser="port = 5432 user = postgres password = somepassword "`

than I've started CS with:

`./BINARIES/ChatScriptpg local`

but it still did not create any tables in DB: not in postgres db, and users db also is not created:

```
postgres=# \d
No relations found.
postgres=# \c users
FATAL:  database "users" does not exist
Previous connection kept
```

At the same time data is still writing to files inside  USERS folder. Actually I need it because we want to have multiple CS servers all connecting to a common Postgres DB machine so a user can be routed to any server.

Could you suggest something or tell what I'm missing? Maybe it's needed to pass some paramters to CS binary when I start it?

**Comment by yulstewartgurrea** [comment]
@unsigned6 have you encountered this problem?

POSTGRES:  Dbinit failed - hostaddr = 127.0.0.1 port = 5,432 user = postgres password = newpassword - could not match 2 port numbers to 1 hosts

if so, how did you resolved it? im using ubuntu btw.
