### ISSUE TITLE
buildfiles commandline

### ISSUE THREAD

**Issue by jb-kerboeuf** [bwilcox-1234/ChatScript#90]
Hi ! 
The `buildfiles=...` commandline doesn't work.  
I located the bug but for whatever reason, I can't upload anything on GitHub with a clean diff... So here it is: 

In scriptCompile.cpp line 5170
`sprintf(file, (char*)"%s/%s", name,buildfiles);`

Should be
`sprintf(file, (char*)"%s/%s", buildfiles, name);`

That's all :)

**Comment by bwilcox-1234** [comment]
fixed in src, not recompiled any binaries
