### ISSUE TITLE
[UDATED] Unable to use Postgres as a replacement for the local file system of the USERS directory.

### ISSUE THREAD

**Issue by unsigned6** [bwilcox-1234/ChatScript#91]
Thanks for answer to my previous  issue #88 . I've made build and tried again with new CS binary for postgres but still don't have storing data from USERS in database. Btw, I tried with this new binary your postgres chatbot and it actually has connection with DB - i was able to connect, create table. Here is credentials which I used in ^dbinit:

`u: (open)  if (^dbinit( dbname = postgres port = 5432 user = postgres password = somepassword  )) {db opened}`

as a result connection is really working ():

```
POSTGRES:  Ready- type: open, table, tables, store, list, drop, or close
test: > open
POSTGRES:  Db opened
test: > table
POSTGRES:  Table s created
test: > store
POSTGRES:  Completed
test: > list
POSTGRES:  1
 Completed
```
and this is what I set to pguser variable (in bash) before starting CS:

`pguser="port = 5432 user = postgres password = somepassword "`

than I've started CS with:

`./BINARIES/ChatScriptpg local`

but it still did not create any tables in DB: not in postgres db, and users db also is not created:

```
postgres=# \d
No relations found.
postgres=# \c users
FATAL:  database "users" does not exist
Previous connection kept
```

At the same time data is still writing to files inside  USERS folder. Actually I need it because we want to have multiple CS servers all connecting to a common Postgres DB machine so a user can be routed to any server.

Could you suggest something or tell what I'm missing? Maybe it's needed to pass some paramters to CS binary when I start it?

**Comment by bwilcox-1234** [comment]
pguser="port = 5432 user = postgres password = somepassword "  is a command line parameter to pass to chatscript, not a bash variable.
