### ISSUE TITLE
InitSystem + CloseSystem + InitSystem can crash: logmainbuffer invalid (freed)

### ISSUE THREAD

**Issue by TheWesson** [bwilcox-1234/ChatScript#97]
Around line 870 in mainSystem.cpp in function CloseSystem(..), logmainbuffer is freed, but not set to NULL.

`	if (logmainbuffer) free(logmainbuffer);`
`	if (ourMainOutputBuffer) free(ourMainOutputBuffer);`
`}`

When InitSystem(..) is called again, logmainbuffer is not NULL so does not get a new malloc (despite having been free'd) so invalid memory gets written to.

`os.cpp:1580:    char* logbase = logmainbuffer;`
`os.cpp:1581:    if (!logbase) logmainbuffer = logbase = (char*) malloc(logsize);`

This can cause a problem if loading a new ChatBot in the same process (depending on exactly what happens to the memory free'd from logmainbuffer.)

**Comment by TheWesson** [comment]
This would be fixed by setting logmainbuffer to NULL after it is freed in CloseSystem

**Comment by bwilcox-1234** [comment]
fixed in next release, maybe this weekend, maybe not
